---
title: "Demo 2"
author: "Evan “Pete” Walsh"
date: "November 22, 2014"
output: ioslides_presentation
runtime: shiny
---

## Shiny Presentation

For the interactive googleVis component displayed through Shiny to work properly, the presentation needs to be opened to that slide initially, otherwise the map will not render properly.

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Slide with Interactive Plot

```{r, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, 
       breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with interactive googleVis map

```{r, echo=FALSE}
suppressPackageStartupMessages(require(dplyr))
suppressPackageStartupMessages(require(googleVis))
dinner <- read.csv("/Users/marianwaitwalsh/Github/STAT-579-Final-Project/Data/Restaurants/dinner.csv")
df <- dinner %>% select(c(26, 27, 28, 32)) %>% 
  mutate(location = paste(as.character(latitude), as.character(longitude),
                          sep = ":"),
         tip = name %>% paste(as.character(stars), sep = ": ") %>%
           paste("stars", sep = " "))
output$map <- renderGvis({
  gvis1 <- gvisMap(df, "location", "tip",
                 options = list(showTip = TRUE, 
                                enableScrollWheel = TRUE,
                                useMapTypeControl = TRUE,
                                mapType = "normal"))
  gvis1
})

htmlOutput("map")
```


