---
title: "Analysis of the Yelp Academic Dataset"
author: "Chelsey Legacy, Lindong Zhou, Evan “Pete” Walsh"
date: "November 22, 2014"
output: 
  ioslides_presentation:
    logo: logo.jpg
runtime: shiny
---

```{r echo=FALSE}
suppressPackageStartupMessages(require(dplyr))
suppressPackageStartupMessages(require(googleVis))
food <- read.csv("/Users/marianwaitwalsh/Github/STAT-579-Final-Project/Data/Restaurants/food.csv")
```

# Introduction

## Intro

### Dataset

Words

# Data

## Raw data format

Words

$$x^{2} + 3$$

## Data cleaning process | Subtitle


----

```{r, echo=FALSE}
shinyApp(
  ui = fluidPage(responsive = FALSE,
                 fluidRow(style = "padding-bottom: 20px;",
                  column(2, selectInput("place", label = "Region", 
                            levels(food$state), selected = "WI")),
                  column(5, selectInput("type", label = "Type",
                            choices = levels(food$type), 
                            selected = levels(food$type)[1],
                            multiple = TRUE)),
                  column(2, selectInput("lower", label = "Lowest rating",
                            choices = as.character(seq(1,5, by=0.5)),
                            selected = "4")),
                  column(2, selectInput("upper", label = "Highest rating",
                            choices = as.character(seq(1,5,by=0.5)),
                            selected = "5"))),
                 htmlOutput("map")
                 ),
  
  server = function(input, output) {
    dataInput <- reactive({
      df <- food %>% subset(state == input$place, stars > 4) %>%
        filter(type %in% input$type) %>%
        filter(stars >= as.numeric(input$lower) & stars <= as.numeric(input$upper))
    })
    output$map <- renderGvis({
      gvis1 <- gvisMap(dataInput(), "location", "tip",
                 options = list(showTip = TRUE, 
                                enableScrollWheel = TRUE,
                                useMapTypeControl = TRUE,
                                mapType = "normal"))
      gvis1
    })
  }
)
```


